#!/usr/bin/env python

from operator import itemgetter
import sys

current_key = None
sum = 0

# input comes from STDIN
for line in sys.stdin:
	# remove leading and trailing whitespace
	line = line.strip()
	row = line.split("\t")
	(key,value) = row

	try: 
		value = int(value)
	except ValueError:
		continue

	# this IF-switch only works because Hadoop sorts map output
	# by key (here: word) before it is passed to the reducer
	if current_key == key:
		sum += value
	else:
		if current_key:
	 		# write result to STDOUT
			print('{}\t{}'.format(current_key,sum,timestamp_ms,timestamp_str))
		current_key = key
		sum = value

#Last key
if current_key == key:
	print('{}\t{}'.format(current_key,sum,timestamp_ms,timestamp_str))
